# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '5'
  Patch: '2'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.0'
  inputs:
    version: 3.0.100
- script: 'dotnet tool restore'
  displayName: 'dotnet tool restore'
- script: 'dotnet dotnet-gitversion /output buildserver /nofetch'
  displayName: 'set GitVersion'
  workingDirectory: src
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    projects: src/**/*.csproj
    custom: pack
    arguments: "--output $(Build.ArtifactStagingDirectory) --include-symbols /p:Configuration=$(BuildConfiguration) --verbosity Normal /p:Version=$(GitVersion.NuGetVersion)"
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'
    verbosityPush: 'Normal'
  